export const SHOW_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const LOGOUT_USER = 'LOGOUT_USER'

// Login Actions
export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

// Vendor --> Product Creation Action
export const VENDOR_CREATE_PRODUCT_BEGIN = 'VENDOR_CREATE_PRODUCT_BEGIN'
export const VENDOR_CREATE_PRODUCT_SUCCESS = 'VENDOR_CREATE_PRODUCT_SUCCESS'
export const VENDOR_CREATE_PRODUCT_ERROR = 'VENDOR_CREATE_PRODUCT_ERROR'

// Vendor --> Product Image Uploading Action
export const VENDOR_IMAGES_UPLOAD_BEGIN = 'VENDOR_IMAGES_UPLOAD_BEGIN'
export const VENDOR_IMAGES_UPLOAD_SUCCESS = 'VENDOR_IMAGES_UPLOAD_SUCCESS'
export const VENDOR_IMAGES_UPLOAD_ERROR = 'VENDOR_IMAGES_UPLOAD_ERROR'

// Get Products
export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'

// Adding to Wishlist
export const ADD_TO_WISHLIST_BEGIN = 'ADD_TO_WISHLIST_BEGIN'
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS'
export const ADD_TO_WISHLIST_ERROR = 'ADD_TO_WISHLIST_ERROR'

// Removing from Wishlist
export const REMOVE_FROM_WISHLIST_BEGIN = 'REMOVE_FROM_WISHLIST_BEGIN'
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS'
export const REMOVE_FROM_WISHLIST_ERROR = 'REMOVE_FROM_WISHLIST_ERROR'

// Updating Cart
export const UPDATE_CART = "UPDATE_CART"

// Submit Order
export const SUBMIT_ORDER_BEGIN = "SUBMIT_ORDER_BEGIN"
export const SUBMIT_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS"
export const SUBMIT_ORDER_ERROR = "SUBMIT_ORDER_ERROR"


// Update User
export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"


// clear cart
export const CLEAR_CART = "CLEAR_CART";