export const SHOW_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const LOGOUT_USER = 'LOGOUT_USER'

// Login Actions
export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

// Vendor --> Product Creation Action
export const VENDOR_CREATE_PRODUCT_BEGIN = 'VENDOR_CREATE_PRODUCT_BEGIN'
export const VENDOR_CREATE_PRODUCT_SUCCESS = 'VENDOR_CREATE_PRODUCT_SUCCESS'
export const VENDOR_CREATE_PRODUCT_ERROR = 'VENDOR_CREATE_PRODUCT_ERROR'

// Vendor --> Product Image Uploading Action
export const VENDOR_IMAGES_UPLOAD_BEGIN = 'VENDOR_IMAGES_UPLOAD_BEGIN'
export const VENDOR_IMAGES_UPLOAD_SUCCESS = 'VENDOR_IMAGES_UPLOAD_SUCCESS'
export const VENDOR_IMAGES_UPLOAD_ERROR = 'VENDOR_IMAGES_UPLOAD_ERROR'

// Get Products
export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'